In [1]:
import pandas as pd
import ast

In [2]:
chennai_cars = pd.read_excel("Downloads/cars_data/chennai_cars.xlsx")
kolkata_cars = pd.read_excel("Downloads/cars_data/kolkata_cars.xlsx")
jaipur_cars = pd.read_excel("Downloads/cars_data/jaipur_cars.xlsx")
hyderabad_cars = pd.read_excel("Downloads/cars_data/hyderabad_cars.xlsx")
bangalore_cars = pd.read_excel("Downloads/cars_data/bangalore_cars.xlsx")
delhi_cars = pd.read_excel("Downloads/cars_data/delhi_cars.xlsx")

In [3]:
# Load the provided Excel file to inspect its structure
#file_path = 'Downloads/cars_data/chennai_cars.xlsx'
#excel_data = pd.ExcelFile(file_path)

# Checking sheet names and loading data from the first sheet
#sheet_names = excel_data.sheet_names
#chennai_car_data = excel_data.parse(sheet_names[0])

# Displaying the first few rows of the data to understand its structure

all_cars = pd.concat([chennai_cars,kolkata_cars,jaipur_cars,hyderabad_cars,bangalore_cars,delhi_cars])
all_cars

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Minivans', 'k...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
...,...,...,...,...,...
1480,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1481,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1482,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1483,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1484,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'I...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [4]:

# Extract and expand key-value pairs from relevant columns ('new_car_overview', 'new_car_feature', 'new_car_specs')

# Initialize lists to hold extracted data for each category
overview_data, feature_data, specs_data = [], [], []

# Iterate over each row and process the dictionary columns
for _, row in all_cars.iterrows():
    # Parse each JSON-like string to a dictionary
    try:
        # Convert string representation of dictionaries to actual dictionaries
        overview = ast.literal_eval(row['new_car_overview'])
        feature = ast.literal_eval(row['new_car_feature'])
        specs = ast.literal_eval(row['new_car_specs'])
        
        # Extract key-value pairs from 'top' items if they exist in each section
        if 'top' in overview:
            overview_data.append({item['key']: item['value'] for item in overview['top']})
        else:
            overview_data.append({})

        if 'top' in feature:
            feature_data.append({item['value']: True for item in feature['top']})  # Use presence as indicator
        else:
            feature_data.append({})

        if 'top' in specs:
            specs_data.append({item['key']: item['value'] for item in specs['top']})
        else:
            specs_data.append({})

    except (ValueError, SyntaxError):
        # In case of any parsing errors, append empty dictionaries
        overview_data.append({})
        feature_data.append({})
        specs_data.append({})

# Create DataFrames for each category
overview_df = pd.DataFrame(overview_data)
feature_df = pd.DataFrame(feature_data)
specs_df = pd.DataFrame(specs_data)

# Concatenate all extracted data into a single DataFrame
cars_final_df = pd.concat([overview_df, feature_df, specs_df], axis=1)
cars_final_df

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture,...,Side Air Bag Front,Cruise Control,Drive Modes,Digital Clock,Engine,Max Power,Torque,Wheel Size,Seats,Mileage
0,2022,Third Party insurance,Petrol,5 Seats,"20,000 Kms",TN02,First Owner,998 cc,Automatic,2022.0,...,NaN,NaN,NaN,NaN,998 CC,118.36bhp,172nm,16,5,NaN
1,Feb 2015,Comprehensive,Petrol,7 Seats,"20,687 Kms",TN04,First Owner,1196 cc,Manual,2015.0,...,NaN,NaN,NaN,NaN,1196 CC,73bhp,101Nm,NaN,7,15.37 kmpl
2,2021,Third Party insurance,Petrol,5 Seats,"30,000 Kms",TN22,First Owner,999 cc,Manual,2021.0,...,NaN,NaN,NaN,NaN,999 CC,98.63bhp,160Nm,16,5,20 kmpl
3,May 2015,Comprehensive,Petrol,5 Seats,"59,247 Kms",TN11,First Owner,1086 cc,Manual,2015.0,...,NaN,NaN,NaN,NaN,1086 CC,68.05bhp,99.04Nm,NaN,5,19.81 kmpl
4,2015,Third Party insurance,Petrol,5 Seats,"50,000 Kms",KA03,First Owner,1199 cc,Manual,2015.0,...,NaN,NaN,NaN,NaN,1199 CC,88.7bhp,110Nm,15,5,18.7 kmpl
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,2019,Third Party insurance,Petrol,5 Seats,"60,000 Kms",DL4C,First Owner,1497 cc,Automatic,2019.0,...,NaN,NaN,NaN,NaN,1497 CC,117.6bhp,145Nm,15,5,18 kmpl
8365,2021,Third Party insurance,Petrol,5 Seats,"20,000 Kms",NaN,First Owner,1197 cc,Manual,2021.0,...,NaN,NaN,NaN,NaN,1197 CC,81.86bhp,115Nm,NaN,5,18.4 kmpl
8366,2011,Third Party insurance,Petrol,5 Seats,"60,000 Kms",NaN,First Owner,1591 cc,Manual,2011.0,...,NaN,NaN,NaN,NaN,1591 CC,121.3bhp,154.9Nm,16,5,17.01 kmpl
8367,Oct 2019,Third Party insurance,Diesel,5 Seats,"38,000 Kms",HR26,First Owner,1582 cc,Manual,2019.0,...,NaN,NaN,NaN,NaN,1582 CC,126.2bhp,259.87NM,17,5,20.5 kmpl
8368,NaN,Third Party insurance,Diesel,6 Seats,"7,000 Kms",NaN,NaN,1996 cc,Automatic,2023.0,...,NaN,NaN,NaN,NaN,1996 CC,212.55bhp,478.5Nm,19,6,12.04 kmpl

In [6]:
cars_final_df.columns

Index(['Registration Year', 'Insurance Validity', 'Fuel Type', 'Seats',
       'Kms Driven', 'RTO', 'Ownership', 'Engine Displacement', 'Transmission',
       'Year of Manufacture', 'Power Steering', 'Power Windows Front',
       'Air Conditioner', 'Heater', 'Adjustable Head Lights',
       'Fog Lights Front', 'Anti Lock Braking System', 'Brake Assist', 'Radio',
       'Low Fuel Warning Light', 'Accessory Power Outlet', 'Digital Odometer',
       'Manually Adjustable Exterior Rear View Mirror', 'Child Safety Locks',
       'Centeral Locking', 'Power Door Locks', 'Cd Player',
       'Power Adjustable Exterior Rear View Mirror', 'Speakers Front',
       'Remote Trunk Opener', 'Day Night Rear View Mirror',
       'Passenger Side Rear View Mirror', 'Fog Lights Rear', 'Tachometer',
       'Power Antenna', 'Cassette Player', 'Air Quality Control',
       'Driver Air Bag', 'Dvd Player', 'Number Of Speaker', 'Tinted Glass',
       'Halogen Headlamps', 'Usb Auxiliary Input', 'Fabric Upholstery',
       'Anti Theft Alarm', 'Power Windows Rear', 'Electronic Multi Tripmeter',
       'Leather Seats', 'Trunk Light', 'Vanity Mirror', 'Glove Compartment',
       'Audio System Remote Control', 'Remote Fuel Lid Opener', 'Wheel Covers',
       'Rear Window Defogger', 'Rear Seat Headrest', 'Cd Changer',
       'Adjustable Seats', 'Tyre Pressure Monitor', 'Touch Screen',
       'Electric Folding Rear View Mirror', 'Alloy Wheels',
       'Leather Steering Wheel', 'Cup Holders Front', 'LEDDRLs',
       'Adjustable Steering', 'Integrated2Din Audio', 'Bluetooth',
       'Rear Seat Belts', 'Rear Spoiler', 'Rear Window Wiper',
       'Integrated Antenna', 'Navigation System', 'Passenger Air Bag',
       'Rear Folding Table', 'Driving Experience Control Eco',
       'Engine Immobilizer', 'Speakers Rear', 'Multifunction Steering Wheel',
       'Sun Roof', 'Moon Roof', 'Side Air Bag Front', 'Cruise Control',
       'Drive Modes', 'Digital Clock', 'Engine', 'Max Power', 'Torque',
       'Wheel Size', 'Seats', 'Mileage'],
      dtype='object')

In [8]:
all_cars['new_car_detail'][0]

<bound method Series.info of 0    {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
0    {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
0    {'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...
0    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
0    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
0    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
Name: new_car_detail, dtype: object>

In [10]:
cars_data = all_cars.copy()

In [11]:
cars_data['new_car_detail_dict'] = cars_data['new_car_detail'].apply(ast.literal_eval)

cars_data['fuel_type'] = cars_data['new_car_detail_dict'].apply(lambda x: x.get('ft'))
cars_data['body_type'] = cars_data['new_car_detail_dict'].apply(lambda x: x.get('bt'))
cars_data['kilometers_driven'] = cars_data['new_car_detail_dict'].apply(lambda x: x.get('km'))
cars_data['OEM'] = cars_data['new_car_detail_dict'].apply(lambda x: x.get('oem'))
cars_data['model'] = cars_data['new_car_detail_dict'].apply(lambda x: x.get('model'))
cars_data['model_year'] = cars_data['new_car_detail_dict'].apply(lambda x: x.get('modelYear'))
cars_data['price'] = cars_data['new_car_detail_dict'].apply(lambda x: x.get('price'))
cars_data['Owner'] = cars_data['new_car_detail_dict'].apply(lambda x: x.get('owner'))
cars_data['Variant_name'] = cars_data['new_car_detail_dict'].apply(lambda x: x.get('variantName'))

In [12]:
cars_data['name'] = cars_data['model']+' '+(cars_data['Variant_name'])
cars_data['name']

0       Kia Sonet Turbo DCT Anniversary Edition
1            Maruti Eeco 7 Seater Standard BSIV
2          Nissan Magnite Turbo XV Premium BSVI
3                       Hyundai i10 Sportz 1.1L
4                      Honda Jazz 1.2 VX i VTEC
                         ...
1480                    Honda City i-VTEC CVT V
1481                    Kia Sonet HTK Plus BSVI
1482                  Hyundai Verna 1.6 SX VTVT
1483         Hyundai Creta 1.6 SX Option Diesel
1484                 MG Gloster Savvy 6 Str 4x4
Name: name, Length: 8369, dtype: object

In [14]:
cars_data_detail  = cars_data[['fuel_type','body_type','kilometers_driven','OEM','model','model_year','price','Owner','Variant_name','name']]
print(cars_data_detail)

     fuel_type  body_type kilometers_driven      OEM           model  \
0       Petrol        SUV            20,000      Kia       Kia Sonet
1       Petrol   Minivans            20,687   Maruti     Maruti Eeco
2       Petrol        SUV            30,000   Nissan  Nissan Magnite
3       Petrol  Hatchback            59,247  Hyundai     Hyundai i10
4       Petrol  Hatchback            50,000    Honda      Honda Jazz
...        ...        ...               ...      ...             ...
1480    Petrol      Sedan            60,000    Honda      Honda City
1481    Petrol        SUV            20,000      Kia       Kia Sonet
1482    Petrol      Sedan            60,000  Hyundai   Hyundai Verna
1483    Diesel        SUV            38,000  Hyundai   Hyundai Creta
1484    Diesel        SUV             7,000       MG      MG Gloster

      model_year         price      Owner                   Variant_name  \
0           2022  â‚¹ 11.50 Lakh  1st Owner  Turbo DCT Anniversary Edition
1           2015   â‚¹ 4.15 Lakh  1st Owner         7 Seater Standard BSIV
2           2021   â‚¹ 7.50 Lakh  1st Owner          Turbo XV Premium BSVI
3           2015   â‚¹ 3.98 Lakh  1st Owner                    Sportz 1.1L
4           2015   â‚¹ 5.50 Lakh  1st Owner                  1.2 VX i VTEC
...          ...           ...        ...                            ...
1480        2019      â‚¹ 9 Lakh  1st Owner                   i-VTEC CVT V
1481        2021   â‚¹ 9.50 Lakh  1st Owner                  HTK Plus BSVI
1482        2011   â‚¹ 4.18 Lakh  1st Owner                    1.6 SX VTVT
1483        2019  â‚¹ 11.95 Lakh  1st Owner           1.6 SX Option Diesel
1484        2023  â‚¹ 46.40 Lakh  0th Owner                Savvy 6 Str 4x4

                                         name
0     Kia Sonet Turbo DCT Anniversary Edition
1          Maruti Eeco 7 Seater Standard BSIV
2        Nissan Magnite Turbo XV Premium BSVI
3                     Hyundai i10 Sportz 1.1L
4                    Honda Jazz 1.2 VX i VTEC
...                                       ...
1480                  Honda City i-VTEC CVT V
1481                  Kia Sonet HTK Plus BSVI
1482                Hyundai Verna 1.6 SX VTVT
1483       Hyundai Creta 1.6 SX Option Diesel
1484               MG Gloster Savvy 6 Str 4x4

[8369 rows x 10 columns]

In [22]:
cars_data_details = pd.DataFrame(cars_data_detail)
cars_data_details

,fuel_type,body_type,kilometers_driven,OEM,model,model_year,price,Owner,Variant_name,name
0,Petrol,SUV,"20,000",Kia,Kia Sonet,2022,â‚¹ 11.50 Lakh,1st Owner,Turbo DCT Anniversary Edition,Kia Sonet Turbo DCT Anniversary Edition
1,Petrol,Minivans,"20,687",Maruti,Maruti Eeco,2015,â‚¹ 4.15 Lakh,1st Owner,7 Seater Standard BSIV,Maruti Eeco 7 Seater Standard BSIV
2,Petrol,SUV,"30,000",Nissan,Nissan Magnite,2021,â‚¹ 7.50 Lakh,1st Owner,Turbo XV Premium BSVI,Nissan Magnite Turbo XV Premium BSVI
3,Petrol,Hatchback,"59,247",Hyundai,Hyundai i10,2015,â‚¹ 3.98 Lakh,1st Owner,Sportz 1.1L,Hyundai i10 Sportz 1.1L
4,Petrol,Hatchback,"50,000",Honda,Honda Jazz,2015,â‚¹ 5.50 Lakh,1st Owner,1.2 VX i VTEC,Honda Jazz 1.2 VX i VTEC
...,...,...,...,...,...,...,...,...,...,...
1480,Petrol,Sedan,"60,000",Honda,Honda City,2019,â‚¹ 9 Lakh,1st Owner,i-VTEC CVT V,Honda City i-VTEC CVT V
1481,Petrol,SUV,"20,000",Kia,Kia Sonet,2021,â‚¹ 9.50 Lakh,1st Owner,HTK Plus BSVI,Kia Sonet HTK Plus BSVI
1482,Petrol,Sedan,"60,000",Hyundai,Hyundai Verna,2011,â‚¹ 4.18 Lakh,1st Owner,1.6 SX VTVT,Hyundai Verna 1.6 SX VTVT
1483,Diesel,SUV,"38,000",Hyundai,Hyundai Creta,2019,â‚¹ 11.95 Lakh,1st Owner,1.6 SX Option Diesel,Hyundai Creta 1.6 SX Option Diesel
1484,Diesel,SUV,"7,000",MG,MG Gloster,2023,â‚¹ 46.40 Lakh,0th Owner,Savvy 6 Str 4x4,MG Gloster Savvy 6 Str 4x4

In [23]:
final_data = cars_data_details.join(cars_final_df)
final_data

,fuel_type,body_type,kilometers_driven,OEM,model,model_year,price,Owner,Variant_name,name,...,Side Air Bag Front,Cruise Control,Drive Modes,Digital Clock,Engine,Max Power,Torque,Wheel Size,Seats,Mileage
0,Petrol,SUV,"20,000",Kia,Kia Sonet,2022,â‚¹ 11.50 Lakh,1st Owner,Turbo DCT Anniversary Edition,Kia Sonet Turbo DCT Anniversary Edition,...,NaN,NaN,NaN,NaN,998 CC,118.36bhp,172nm,16,5,NaN
0,Petrol,Sedan,"70,000",Toyota,Toyota Camry,2014,â‚¹ 9.75 Lakh,3rd Owner,Hybrid,Toyota Camry Hybrid,...,NaN,NaN,NaN,NaN,998 CC,118.36bhp,172nm,16,5,NaN
0,Diesel,Hatchback,"1,20,000",Hyundai,Hyundai i20,2015,â‚¹ 5.10 Lakh,2nd Owner,Asta 1.4 CRDi,Hyundai i20 Asta 1.4 CRDi,...,NaN,NaN,NaN,NaN,998 CC,118.36bhp,172nm,16,5,NaN
0,Petrol,Hatchback,"20,000",Volkswagen,Volkswagen Polo,2022,â‚¹ 10.44 Lakh,1st Owner,1.0 TSI Highline Plus AT,Volkswagen Polo 1.0 TSI Highline Plus AT,...,NaN,NaN,NaN,NaN,998 CC,118.36bhp,172nm,16,5,NaN
0,Petrol,Hatchback,"1,20,000",Maruti,Maruti Celerio,2015,â‚¹ 4 Lakh,3rd Owner,VXI,Maruti Celerio VXI,...,NaN,NaN,NaN,NaN,998 CC,118.36bhp,172nm,16,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481,Petrol,SUV,"20,000",Kia,Kia Sonet,2021,â‚¹ 9.50 Lakh,1st Owner,HTK Plus BSVI,Kia Sonet HTK Plus BSVI,...,NaN,NaN,NaN,NaN,1498 CC,98.6bhp,200Nm,15,5,25.1 kmpl
1482,Diesel,MUV,"1,00,000",Toyota,Toyota Innova,2015,â‚¹ 15 Lakh,1st Owner,2.5 ZX Diesel 7 Seater,Toyota Innova 2.5 ZX Diesel 7 Seater,...,NaN,NaN,NaN,NaN,1086 CC,68.07bhp,99.07Nm,NaN,5,20.3 kmpl
1482,Petrol,Sedan,"60,000",Hyundai,Hyundai Verna,2011,â‚¹ 4.18 Lakh,1st Owner,1.6 SX VTVT,Hyundai Verna 1.6 SX VTVT,...,NaN,NaN,NaN,NaN,1086 CC,68.07bhp,99.07Nm,NaN,5,20.3 kmpl
1483,Diesel,SUV,"38,000",Hyundai,Hyundai Creta,2019,â‚¹ 11.95 Lakh,1st Owner,1.6 SX Option Diesel,Hyundai Creta 1.6 SX Option Diesel,...,NaN,NaN,NaN,NaN,999 CC,67bhp,91Nm,NaN,5,21.74 kmpl
1484,Diesel,SUV,"7,000",MG,MG Gloster,2023,â‚¹ 46.40 Lakh,0th Owner,Savvy 6 Str 4x4,MG Gloster Savvy 6 Str 4x4,...,NaN,NaN,NaN,NaN,1199 CC,88.7bhp,110Nm,16,5,17.5 kmpl

In [24]:
final_data.to_csv("Downloads\Final_cars_data.csv")